### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ugurkorkmaz** [pucose/pucose#1]
# I am creating a roadmap for the project, there may be changes.

- [ ] Prepare the infrastructure skeleton.
- [ ] Set up the database schema.
- [ ] Set up restfull api scheme.
- [ ] Write documentation with Swagger.

<hr />

###  In this project, git commits are made sematically. 
- `feat`: new feature for the user, not a new feature for build script.
- `fix`: bug fix for the user, not a fix to a build script.
- `docs`: changes to the documentation.
- `style`: formatting, missing semi colons, etc; no production code change.
- `refactor`: refactoring production code, eg. renaming a variable.
- `test`: adding missing tests, refactoring tests; no production code change.
- `chore`: updating grunt tasks etc; no production code change.
 [Sematically comment resource](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)
